Repository drand/drand, pull requests merged in 2022-04, with the labels that each got.

#798 Stream management
  .github/workflows/generate.yml
  chain/beacon/chain.go
  chain/beacon/node.go
  chain/beacon/node_test.go
  chain/beacon/sync.go
  chain/beacon/sync_manager.go
  chain/boltdb/store_test.go
  chain/info.go
  core/drand_beacon_control.go
  core/drand_beacon_public.go
  core/drand_test.go
  net/client_grpc.go
  net/peer.go
  protobuf/common/common.pb.go
  protobuf/crypto/dkg/dkg.pb.go
  protobuf/drand/api.pb.go
  protobuf/drand/api_grpc.pb.go
  protobuf/drand/common.pb.go
  protobuf/drand/control.pb.go
  protobuf/drand/control_grpc.pb.go
  protobuf/drand/protocol.pb.go
  protobuf/drand/protocol_grpc.pb.go
Labels: refactoring

#955 Emit DKG/Reshare status when node starts up/shuts down
  core/drand_daemon.go
  metrics/metrics.go
Labels: monitoring

#956 Set version in source instead of injecting via ldflags
  .github/workflows/regression.yml
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile
  chain/beacon/node_test.go
  common/constants.go
  common/version.go
  common/version_test.go
  core/broadcast_test.go
  core/drand_daemon_interceptors.go
  go.mod
  go.sum
  key/group_test.go
  protobuf/common/common.pb.go
  protobuf/common/common.proto
  test/docker/Dockerfile
Labels: monitoring

#960 Fix burning in the commit ID into the binary
  Makefile
  core/drand_daemon_interceptors.go
Labels: monitoring

#959 Add incoming/outgoing connections metrics
  metrics/metrics.go
  net/client_grpc.go
  net/listener.go
  net/metrics.go
Labels: monitoring

#962 Avoiding concurrent CI actions
  .github/workflows/lint.yml
  .github/workflows/regression.yml
  .github/workflows/tests.yaml
Labels: testing, refactoring

#958 Cherry-picking from release/v1.3.0
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yaml
  .github/workflows/publish_tagged.yaml
  .github/workflows/regression.yml
  .github/workflows/tests.yaml
  Makefile
  chain/beacon/node.go
  go.mod
  go.sum
  http/server.go
  http/server_test.go
  lp2p/addrutil_test.go
  lp2p/ctor.go
  metrics/metrics.go
  net/peer.go
  protobuf/common/common.pb.go
  protobuf/crypto/dkg/dkg.pb.go
  protobuf/drand/api.pb.go
  protobuf/drand/common.pb.go
  protobuf/drand/control.pb.go
  protobuf/drand/protocol.pb.go
Labels: refactoring

#969 Add the beacon ID to some metrics
  chain/beacon/store.go
  metrics/metrics.go
Labels: monitoring

#971 Enable the is_drand_node metric and add state change timestamp metrics
  metrics/metrics.go
Labels: monitoring

#970 Preparing testnet release.
  .github/workflows/release.yml
  common/version.go
Labels: bug
