Repository drand/drand, pull requests merged in 2022-06, with the labels that each got.

#1017 Send metrics over GRPC even if the node is not in the `default` network (#1008)
  common/beacon.go
  core/drand_beacon_metrics.go
  core/drand_daemon.go
  metrics/metrics.go
  metrics/metrics_test.go
Labels: monitoring

#1024 Removing start credits
  README.md
  cmd/drand-cli/cli.go
Labels: refactoring

#1030 No panic on creation of drand daemon on bound port
  cmd/drand-cli/cli_test.go
  core/drand_daemon.go
  core/drand_daemon_test.go
  net/control.go
  net/control_test.go
Labels: bug
